<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AddNewProductsService" targetNamespace="http://ws.camel.application.demo.shopping.redhat.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.camel.application.demo.shopping.redhat.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://ws.camel.application.demo.shopping.redhat.com/" schemaLocation="AddNewProductsService_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="addProduct">
    <wsdl:part name="parameters" element="tns:addProduct">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="addProductResponse">
    <wsdl:part name="parameters" element="tns:addProductResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="AddNewProducts">
    <wsdl:operation name="addProduct">
      <wsdl:input name="addProduct" message="tns:addProduct">
    </wsdl:input>
      <wsdl:output name="addProductResponse" message="tns:addProductResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AddNewProductsServiceSoapBinding" type="tns:AddNewProducts">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="addProduct">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="addProduct">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="addProductResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AddNewProductsService">
    <wsdl:port name="AddNewProductsPort" binding="tns:AddNewProductsServiceSoapBinding">
      <soap:address location="http://localhost:8080/shoppingApplication/AddNewProductsService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
