/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Feb 05 18:15:57 IST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.codehaus.jackson.annotate.JsonProperty;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;

/**
 * Salesforce DTO for SObject ProductsObject__c
 */
@XStreamAlias("ProductsObject__c")
public class ProductsObject__c extends AbstractSObjectBase {

    // ProductItemName__c
    private String ProductItemName__c;

    @JsonProperty("ProductItemName__c")
    public String getProductItemName__c() {
        return this.ProductItemName__c;
    }

    @JsonProperty("ProductItemName__c")
    public void setProductItemName__c(String ProductItemName__c) {
        this.ProductItemName__c = ProductItemName__c;
    }

    // ProductItemPrice__c
    private Double ProductItemPrice__c;

    @JsonProperty("ProductItemPrice__c")
    public Double getProductItemPrice__c() {
        return this.ProductItemPrice__c;
    }

    @JsonProperty("ProductItemPrice__c")
    public void setProductItemPrice__c(Double ProductItemPrice__c) {
        this.ProductItemPrice__c = ProductItemPrice__c;
    }

}
