
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.redhat.shopping.demo.application.camel.ws;


import org.apache.log4j.Logger;

/**
 * This class was generated by Apache CXF 2.7.0.redhat-610379
 * 2015-08-30T11:03:03.887-04:00
 * Generated source version: 2.7.0.redhat-610379
 * 
 */

@javax.jws.WebService(
                      serviceName = "AddNewProductsService",
                      portName = "AddNewProductsPort",
                      targetNamespace = "http://ws.camel.application.demo.shopping.redhat.com/",
                      endpointInterface = "com.redhat.shopping.demo.application.camel.ws.AddNewProducts")
                      
public class AddNewProductsImpl implements AddNewProducts {

    private static final Logger LOG = Logger.getLogger(AddNewProductsImpl.class.getName());

    /* (non-Javadoc)
     * @see com.redhat.shopping.demo.application.camel.ws.AddNewProducts#addProduct(java.lang.String  arg0 )*
     */
    public java.lang.String addProduct(java.lang.String arg0) { 
        LOG.warn("Executing addProduct() directly. If you see this message - you are NOT going through the camel route");
        LOG.info(arg0);
        return null;
    }

}
