/*
 * Salesforce Query DTO generated by camel-salesforce-maven-plugin
 * Generated on: Thu Feb 05 18:15:57 IST 2015
 */
package org.apache.camel.salesforce.dto;

import com.thoughtworks.xstream.annotations.XStreamImplicit;
import org.apache.camel.component.salesforce.api.dto.AbstractQueryRecordsBase;

import java.util.List;

/**
 * Salesforce QueryRecords DTO for type ProductsObject__c
 */
public class QueryRecordsProductsObject__c extends AbstractQueryRecordsBase {

    @XStreamImplicit
    private List<ProductsObject__c> records;

    public List<ProductsObject__c> getRecords() {
        return records;
    }

    public void setRecords(List<ProductsObject__c> records) {
        this.records = records;
    }
}
